### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by vilkiida** [EssiPry/tiralabra-2022#1]
# Vertaisarvio (la 23.4)
Latasin ohjelman la noin kello 11 aikaan. Peli on kuten repositorioon oli merkattukin vielä lataushetkellä sen verran kesken, ettei sitä pysty vielä itsessään pelaamaan ja se käynnistäessään päätyy virhe ilmoitukseen. Sille luodut 9 yksikkötestiä kuitenkin kaikki menevät läpi.

Pelin tämän hetkiset yksikkötestit testaavat mielestäni oleellisia asioita jo tällähetkellä valmiista funktioista ja näitä oletettavasti tulossa vielä lisääkin. Ainoa mikä minulla pisti silmään oli että yhdessä yksittäisessä unit testissä on nyt monessa useampia "assert" komentoja. Ei tämä kai tavallaan mikään ongelma ole mutta ainakin joissain artikkeleissa mitä katselin mainittiin, että aina parempi mitä vähemmän niitä on per yksi unit test selkeyden kannalta.

Tarkastelin pelin koodia ohjelman laataamisen jälkeen githubista jolloin sinne oli jo näköjään lisätty uusi committi joka sisälsi esim pelilooppi luokan (eli tarkastelemani koodi ei sama kuin pelin lataushetkellä vaan sitä katsoin muutama tunti sen jälkeen). Tämän commitin jälkeen tarkastellessani koodi oli helposti luettavaa ja lisäyksen ansioista jaoteltu vielä entistä paremmin eri luokkiin joka helpottaa tarkastelua lisää. Myös funktiot on pääasiassa hyvin selkeästi nimetty ja muutenkin helppolukuisa, mikä helpottaa pelin tutkimista varsinkin kun varsinainen peli ei ole vielä pelattavissa ja siten tarkasteltavissa. Koodin funktiot on myös pääosin docstringeillä kommentoituna, mikä välitti niiden tarkoituksen ilman siihen enempää perehtymättä.

Minimax algoritmi alpha beta karsinnalla näyttä omiin silmiini melko hyvältä tähän mennessä. Ainoa mitä tuli itselle ajatuksena sitä tarkastellessa on (en ole siis ihan varma tästä), että jos pelilaudan kopioimisen sijaan algoritmissä vain lisäisi lautaan mahdollisen tulevan siirron mukaisen merkin ja poistaisi sen sitten kun on laskenut "arvo" nimisen muuttujan arvon, niin pienentäisikö tämä vaadittavaa tilaa? Tällöin ei tarvitsisi aina tehdä kopiota pelilaudasta vaan vain lisätä ja poistaa siitä vain yksi merkki? Näyttäisi siis minun silmiini kuitenkin toimivan siis ihan täysin hyvin näinkin (ja on ainakin selkeä) mutta on vain ajatus joka tuli mieleen.

Koodissa tuli vastaan muutamia vain kahden merkin muuttujia kuten: "px" "py", "d1" ja "d2", joista ainakin pylintillä tapana herjata (se haluaa että muuttujat vähintään 3-merkkisiä) ja näin se näytti tekevän nytkin. Pylintin antama arvosana oli kuitenkin melko hyvä varsinkin kun kyseessä ei ole vielä valmis projekti.

Satuin myös huomaamaan, että määrittelydokumentissa luki varmaan vahingossa, että kyseessä on 5x5 pelilaudan ristinolla, sillä README.md sanoo kuitenkin että kyseessä on 25x25 pelilauta ja näin näyttäisi myös koodinkin perusteella olevan.

Vaikka pääominaisuudet ovatkin vielä kesken, vaikuttaa projekti yleisesti hyvältä tähän mennessä. Tsemppiä tekemiseen! :D

**Comment by EssiPry** [comment]
Kiitos hyvistä huomioista ja vinkeistä. Ajattelin yksikkötestit jotenkin väärin, eli että testi per metodi ja siksi siellä oli useampi assert. Onneksi on vertaisarvioijia!
